Fix a integer comparison sign issue.
I introduced this, and it's stupid:

mokutil.c: In function 'generate_pw_hash':
mokutil.c:1971:16: error: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Werror=sign-compare]
  if (salt_size > settings_len - (next - settings)) {
                ^

Signed-off-by: Peter Jones <pjones@redhat.com>